{"name": "test_no_such_login", "status": "passed", "description": "Проверка невозможности залогиниться с несуществующим аккаунтом. Получаем ошибку 404", "steps": [{"name": "Логин курьера в системе", "status": "passed", "parameters": [{"name": "payload", "value": "{'login': 'dsmlktoksv', 'password': 'fgjjmbihwr', 'firstName': 'zvyfcvdcwc'}"}], "start": 1716822790618, "stop": 1716822790685}], "start": 1716822790618, "stop": 1716822790686, "uuid": "9ee2a3cc-bc05-4b19-830d-a165e450956e", "historyId": "f8ba477e2ecf698f789d7f765c2b2fc5", "testCaseId": "f8ba477e2ecf698f789d7f765c2b2fc5", "fullName": "tests.test_login_courier.TestLoginCourier#test_no_such_login", "labels": [{"name": "suite", "value": "Ручка /api/v1/courier/login"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "LAPTOP-K"}, {"name": "thread", "value": "11960-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}