{"name": "test_no_such_login", "status": "passed", "description": "Проверка невозможности залогиниться с несуществующим аккаунтом. Получаем ошибку 404", "steps": [{"name": "Логин курьера в системе", "status": "passed", "parameters": [{"name": "payload", "value": "{'login': 'dezfnwyryo', 'password': 'elilqliqsd', 'firstName': 'dnplxgtywv'}"}], "start": 1715276415314, "stop": 1715276415398}], "start": 1715276415314, "stop": 1715276415398, "uuid": "fd7927f1-7750-463c-9eb6-014465daf017", "historyId": "f8ba477e2ecf698f789d7f765c2b2fc5", "testCaseId": "f8ba477e2ecf698f789d7f765c2b2fc5", "fullName": "tests.test_login_courier.TestLoginCourier#test_no_such_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "WIN-BHU1OVNKOHE"}, {"name": "thread", "value": "8772-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}