{"name": "test_accept_order_twice_error", "status": "passed", "description": "Проверка невозможности принятия заказа, если его уже взяли в работу. Получаем код 409 и сообщение 'Этот заказ уже в работе'", "steps": [{"name": "Принять заказ и получить его id", "status": "passed", "steps": [{"name": "Создание заказа", "status": "passed", "parameters": [{"name": "payload", "value": "'{\"firstName\": \"\\u0410\\u043d\\u0442\\u043e\\u043d\\u0438\\u043d\\u0430\", \"lastName\": \"\\u0412\\u043e\\u0440\\u043e\\u0431\\u044c\\u0435\\u0432\\u0430\", \"address\": \"\\u043a. \\u0412\\u0435\\u0440\\u0445\\u043e\\u0442\\u0443\\u0440\\u044c\\u0435, \\u043f\\u0440. \\u0422\\u0440\\u0430\\u043a\\u0442\\u043e\\u0440\\u043d\\u044b\\u0439, \\u0434. 6/6 \\u0441\\u0442\\u0440. 86, 807178\", \"metroStation\": 9, \"phone\": \"8 778 959 7147\", \"rentTime\": 0, \"deliveryDate\": \"1972-12-02\", \"color\": \"BLACK\", \"comment\": \"\\u041b\\u0430\\u043f\\u0430.\"}'"}], "start": 1715276388449, "stop": 1715276388542}, {"name": "Получить заказ по его номеру", "status": "passed", "parameters": [{"name": "track_number", "value": "922937"}], "start": 1715276388542, "stop": 1715276388665}], "start": 1715276388399, "stop": 1715276388665}, {"name": "Создание и Логин курьера в системе", "status": "passed", "parameters": [{"name": "payload", "value": "{'login': 'mdvrhzgbgt', 'password': 'ybtuslqjzx', 'firstName': 'zuablpuptu'}"}], "start": 1715276388665, "stop": 1715276388820}, {"name": "Принять заказ", "status": "passed", "parameters": [{"name": "id_order", "value": "279750"}, {"name": "id_courier", "value": "304388"}], "start": 1715276388820, "stop": 1715276388888}, {"name": "Принять заказ", "status": "passed", "parameters": [{"name": "id_order", "value": "279750"}, {"name": "id_courier", "value": "304388"}], "start": 1715276388889, "stop": 1715276388969}], "start": 1715276388399, "stop": 1715276388969, "uuid": "3c32e380-0ca3-4bc6-9397-1a79d10ee457", "historyId": "25657ea45580c9f35f74fd7fe579c48e", "testCaseId": "25657ea45580c9f35f74fd7fe579c48e", "fullName": "tests.test_accept_order.TestAcceptOrder#test_accept_order_twice_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "WIN-BHU1OVNKOHE"}, {"name": "thread", "value": "8772-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order"}]}